language: bash

# Use container-based infrastructure for quicker build start-up
sudo: false

addons:
  apt:
    sources:
    - debian-sid # Get shellcheck from the Debian repo
    packages:
    - shellcheck

script:
  - shellcheck mac -e SC2039

matrix:
  fast_finish: true

notifications:
  email: false

