language: bash

# Use container-based infrastructure for quicker build start-up
sudo: false

script:
  - shellcheck -e SC2016 -e SC1090 -e SC2039 ./mac

matrix:
  fast_finish: true

notifications:
  email: false

