#!/bin/sh

# Everything you need to get started at Carousell.
# Running the script alone gets you Chrome and Slack installed.
# You can supply additional commands to get additional setup done:
#
# -encrypt : enables FileVault 2
# -dev : installs a set of programming languages and tools for engineers
# -android : installs android studio
#

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

append_to_bshrc() {
  local text="$1" bshrc
  local skip_new_line="${2:-0}"

  bshrc="$HOME/.bash_profile"

  if ! grep -Fqs "$text" "$bshrc"; then
    if [ "$skip_new_line" -eq 1 ]; then
      printf "%s\n" "$text" >> "$bshrc"
    else
      printf "\n%s\n" "$text" >> "$bshrc"
    fi
  fi
}

# shellcheck disable=SC2154
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

if [ ! -d "$HOME/.bin/" ]; then
  mkdir "$HOME/.bin"
fi

if [ ! -f "$HOME/.bash_profile" ]; then
  touch "$HOME/.bash_profile"
fi

# shellcheck disable=SC2016
append_to_bshrc 'export PATH="$HOME/.bin:$PATH"'
append_to_bshrc 'export HOMEBREW_PREFIX="/usr/local"'

HOMEBREW_PREFIX="/usr/local"


if [ -d "$HOMEBREW_PREFIX" ]; then
  if ! [ -r "$HOMEBREW_PREFIX" ]; then
    sudo chown -R "$LOGNAME:admin" /usr/local
  fi
else
  sudo mkdir "$HOMEBREW_PREFIX"
  sudo chflags norestricted "$HOMEBREW_PREFIX"
  sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
fi

if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."
    curl -fsS \
      'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby

    append_to_bshrc '# recommended by brew doctor'

    # shellcheck disable=SC2016
    append_to_bshrc 'export PATH="/usr/local/bin:$PATH"' 1

    export PATH="/usr/local/bin:$PATH"
fi

if brew list | grep -Fq brew-cask; then
  fancy_echo "Uninstalling old Homebrew-Cask ..."
  brew uninstall --force brew-cask
fi

if brew cask list | grep -q "google-chrome" || [ -d "/Applications/Google Chrome.app" ] ; then
  fancy_echo "Chrome already installed, skipping"
else
  brew cask install "google-chrome"
fi

if brew cask list | grep -q "slack" || [ -d "/Applications/Slack.app" ] ; then
    fancy_echo "Slack already installed, skipping"
else
  brew cask install "slack"
fi

if brew cask list | grep -q "tunnelblick" || [ -d "/Applications/Tunnelblick.app" ] ; then
    fancy_echo "Tunnelblick (VPN) already installed, skipping"
else
  brew cask install "tunnelblick"
fi

if brew cask list | grep -q "iterm2" || [ -d "/Applications/iTerm.app" ] ; then
    fancy_echo "iTerm2 already installed, skipping"
else
  brew cask install "iterm2"
fi


for i in "$@" ; do
        if [[ $i == "-dev" ]]  ; then
                fancy_echo "Updating Homebrew formulae ..."
                brew update
                brew tap homebrew/services
                # Unix
                brew install git openssl
                break
        fi
        if [[ $i == "-backend" ]]  ; then
                # Programming languages
                brew install libyaml node python python3 go rbenv ruby-build
                sudo easy_install --upgrade pip
                sudo pip install virtualenv
                sudo pip install virtualenvwrapper

                brew cask install "docker"
                brew install golang

                # shellcheck source=/dev/null
                source "$HOMEBREW_PREFIX/bin/virtualenvwrapper.sh"
                break
        fi
        if [[ $i == "-android" ]]  ; then
                brew cask install java android-studio
                break
        fi
        if [[ $i == "-ios" ]]; then
                gem install cocoapods
                gem install fastlane
                gem install xcode-install
                xcversion install 9.3.1
                brew install rbenv
                echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
                echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
                source ~/.bash_profile
                brew upgrade ruby-build
                rbenv install 2.3.5
                gem install bundler
                rbenv rehash
                bundle install
                brew install carthage
                brew install node
                brew install yarn
                break
        fi
        if [[ $i == "-encrypt" ]]  ; then
                fancy_echo "***********************************"
                fancy_echo "***********************************"
                fancy_echo "*                                 *"
                fancy_echo "* We will now encrypt your laptop *"
                fancy_echo "*                                 *"
                fancy_echo "* Please enter your Macbook's     *"
                fancy_echo "* username and password.          *"
                fancy_echo "*                                 *"
                fancy_echo "***********************************"
                fancy_echo "***********************************"
                sudo fdesetup enable -user "$(whoami)"
                break
        fi

done

if [ -f "$HOME/.laptop.local" ]; then
  fancy_echo "Running your customizations from ~/.laptop.local ..."
  # shellcheck disable=SC1090
  . "$HOME/.laptop.local"
fi
